export const interestsKeys = [
	'books',
	'kinks',
	'tech',
	'outdoors',
	'animals',
	'movies',
	'traveling',
	'socialMedia',
	'videoGames',
	'fashionBeauty',
	'comedy',
	'food',
	'art',
	'fantasyWorlds',
	'sports',
	'yoga',
	'science',
	'astrology',
	'cars',
	'fishing',
	'religion',
	'music',
	'languages',
	'shopping',
	'partying',
	'collecting',
	'crypto',
	'NFT',
	'photo',
	'dancing',
	'podcasting',
	'handcrafting',
	'psychology',
	'volunteering',
] as const;

type InterestsObject = {
	[key in (typeof interestsKeys)[number]]: string;
};
export const interestText: InterestsObject = {
	books: 'Books & writing',
	kinks: 'Kinks',
	tech: 'tech',
	outdoors: 'outdoors',
	animals: 'animals',
	movies: 'animals',
	traveling: 'animals',
	socialMedia: 'animals',
	videoGames: 'animals',
	fashionBeauty: 'animals',
	comedy: 'comedy',
	food: 'food & cooking',
	art: 'art & design',
	fantasyWorlds: 'fantasy worlds',
	sports: 'sports',
	yoga: 'yoga & meditation',
	science: 'science',
	astrology: 'astrology',
	cars: 'cars',
	fishing: 'fishing',
	religion: 'religion',
	music: 'music',
	languages: 'languages',
	shopping: 'shopping',
	partying: 'partying & clubbing',
	collecting: 'collecting',
	crypto: 'crypto',
	NFT: 'NFT',
	photo: 'photo & videography',
	dancing: 'dancing',
	podcasting: 'podcasting',
	handcrafting: 'handcrafting',
	psychology: 'psychology',
	volunteering: 'volunteering',
};
